//! McpServer — domain model (M2.5, F6).
//!
//! SPEC §2.1 is the contract; this module owns the Rust representation.
//! The on-disk shape is `~/.claude/mcp.json` (single file, with
//! `mcpServers` as a name → server map) — see SPEC §2.2 and the F6
//! dataflow in `docs/design/M2.5-dataflow.md`.
//!
//! ## Conventions
//!
//! - **Disk shape ≠ struct shape.** On disk: `{"mcpServers": {"name":
//!   {...}}}`. In the service layer: `Vec<McpServer>` with `name` as
//!   a field, plus a uuid `id` for stable list/toggle keys. The
//!   service owns the disk ↔ struct translation; the domain model
//!   only deals with the struct.
//! - `enabled` defaults to `true` if missing on disk — matches Claude
//!   Code's own default behaviour (a server entry without a
//!   disabled flag is enabled).
//! - `id` is generated client-side (`uuid::Uuid::new_v4().to_string()`)
//!   and is NEVER part of the on-disk map key. The map key is `name`.
//! - `transport` is the discriminant: `stdio` uses `command` + `args`
//!   + `env`; `http` uses `url`. Cross-validation lives in
//!   [`McpServer::validate`].
//!
//! ## Why a fresh struct (not reuse `infrastructure::sql_parser::McpServer`)
//!
//! The F3 SQL parser produces a *parser-shaped* McpServer: id +
//! name + command + args + env + description. F6's write-side
//! needs *more*: transport + enabled + created_at + uuid. Two
//! types, two responsibilities. The service translates between
//! them when bridging a SQL-imported entry to a writeable entry.

use std::collections::HashMap;
use std::path::Path;

use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::domain::is_valid_id;

/// One MCP server entry the user manages from the F6 page.
///
/// Field naming follows the Rust convention `snake_case`; serde's
/// `rename_all` keeps the JSON shape identical for the frontend
/// mirror in `src/types/mcp.ts`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct McpServer {
    /// UUID — stable list/toggle key. Never part of the on-disk
    /// `mcpServers` map key (that is `name`). Generated by
    /// [`McpServer::new`] with `uuid::Uuid::new_v4()`.
    pub id: String,

    /// Display name; ALSO the on-disk map key. Must be non-empty
    /// (validated in [`McpServer::validate`]).
    pub name: String,

    /// Transport discriminant. `Stdio` = `command` + `args` + `env`
    /// are meaningful; `Http` = `url` is meaningful. Validation
    /// enforces that the corresponding fields are populated.
    pub transport: McpTransport,

    /// Stdio transport only — the executable to run (e.g. `npx`).
    /// Ignored (and should be `None`) for Http transport.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,

    /// Stdio transport only — CLI args passed to `command`.
    #[serde(default)]
    pub args: Vec<String>,

    /// Stdio transport only — env vars set when launching.
    #[serde(default)]
    pub env: HashMap<String, String>,

    /// Http transport only — the SSE / streamable-http endpoint URL.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,

    /// Whether the server is enabled. Defaults to `true` when
    /// missing on disk.
    #[serde(default = "default_enabled")]
    pub enabled: bool,

    /// Unix seconds (matches `Provider::created_at` convention).
    pub created_at: i64,
}

fn default_enabled() -> bool {
    true
}

/// Transport discriminant for an MCP server entry. The on-disk
/// `server_config` JSON uses `{"type": "stdio", ...}` or
/// `{"type": "http", ...}` (Claude Code's own format).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "lowercase")]
pub enum McpTransport {
    /// Subprocess transport: `command` + `args` + `env`.
    Stdio,
    /// HTTP / SSE transport: `url`.
    Http,
}

/// Errors from `McpServer` (de)serialisation + validation.
///
/// I/O errors bubble up via `McpError::Io`; serde errors via
/// `McpError::Json`; logic errors have their own variants.
#[derive(Debug, Error)]
pub enum McpError {
    /// `std::fs` error.
    #[error("MCP I/O error: {0}")]
    Io(#[from] std::io::Error),

    /// `serde_json` error.
    #[error("MCP JSON error: {0}")]
    Json(#[from] serde_json::Error),

    /// An entry with the requested `name` already exists in
    /// `mcpServers`. Same deny-policy as F4 (`ProviderError::
    /// AlreadyExists`).
    #[error("MCP server '{0}' already exists")]
    AlreadyExists(String),

    /// The requested `id` was not found in the current list.
    #[error("MCP server with id '{0}' not found")]
    NotFound(String),

    /// `name` is empty, or `transport = stdio` with no `command`,
    /// or `transport = http` with no `url`.
    #[error("MCP server validation failed: {0}")]
    InvalidField(String),
}

impl McpServer {
    /// Build a fresh McpServer with `id = uuid`, `created_at = now`,
    /// `enabled = true`. The service calls this from the F6 "新增"
    /// form. `name` is required; the rest are optional with sensible
    /// defaults.
    pub fn new(
        name: impl Into<String>,
        transport: McpTransport,
        command: Option<String>,
        url: Option<String>,
    ) -> Self {
        Self {
            id: uuid::Uuid::new_v4().to_string(),
            name: name.into(),
            transport,
            command,
            args: Vec::new(),
            env: HashMap::new(),
            url,
            enabled: true,
            created_at: now_unix_secs(),
        }
    }

    /// Read a single `McpServer` from a JSON file.
    ///
    /// Used by tests + the service when reading a *snapshot* of one
    /// server (rare; the service typically reads the whole
    /// `mcp.json`). Kept for symmetry with `Provider::from_json_file`.
    pub fn from_json_file(path: &Path) -> Result<Self, McpError> {
        let bytes = std::fs::read(path)?;
        let s: McpServer = serde_json::from_slice(&bytes)?;
        s.validate()?;
        Ok(s)
    }

    /// Write a single `McpServer` to a JSON file (pretty-printed,
    /// 2-space indent).
    pub fn to_json_file(&self, path: &Path) -> Result<(), McpError> {
        let json = serde_json::to_string_pretty(self)?;
        std::fs::write(path, json)?;
        Ok(())
    }

    /// Validate field invariants. The service calls this after
    /// `from_json`/`serde_json` and before write.
    pub fn validate(&self) -> Result<(), McpError> {
        if self.name.is_empty() {
            return Err(McpError::InvalidField("name must not be empty".into()));
        }
        // id must be a valid slug — this also rejects blank ids.
        if !is_valid_id(&self.id) && !is_uuid_like(&self.id) {
            return Err(McpError::InvalidField(format!(
                "id '{}' must be a UUID",
                self.id
            )));
        }
        match self.transport {
            McpTransport::Stdio => {
                if self.command.as_deref().unwrap_or("").is_empty() {
                    return Err(McpError::InvalidField(
                        "stdio transport requires non-empty command".into(),
                    ));
                }
            }
            McpTransport::Http => {
                if self.url.as_deref().unwrap_or("").is_empty() {
                    return Err(McpError::InvalidField(
                        "http transport requires non-empty url".into(),
                    ));
                }
            }
        }
        Ok(())
    }
}

/// Heuristic: a string looks like a UUID if it has the right
/// shape (8-4-4-4-12 hex digits, separated by `-`). We don't
/// `uuid::Uuid::parse_str` here because the test fixture uses
/// `id: "00000000-0000-0000-0000-000000000000"` style placeholders
/// and we want lenient matching.
///
/// M2.5: this also accepts `Provider`-style slugs (matching
/// `is_valid_id`), so the F3 import path can wire its id through
/// unchanged. The service layer overrides this for the disk
/// representation.
fn is_uuid_like(s: &str) -> bool {
    // 8-4-4-4-12 hex with dashes = 36 chars
    if s.len() != 36 {
        return false;
    }
    let bytes = s.as_bytes();
    for (i, &b) in bytes.iter().enumerate() {
        match i {
            8 | 13 | 18 | 23 => {
                if b != b'-' {
                    return false;
                }
            }
            _ => {
                if !b.is_ascii_hexdigit() {
                    return false;
                }
            }
        }
    }
    true
}

/// Unix seconds — same `std::time::SystemTime` pattern as
/// `Provider::now_unix_secs`. Duplicated locally to keep
/// `domain::mcp_server` self-contained (no cross-module helper
/// dependency).
fn now_unix_secs() -> i64 {
    use std::time::{SystemTime, UNIX_EPOCH};
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs() as i64)
        .unwrap_or(0)
}

// ---------------------------------------------------------------------------
// Tests — TDD coverage for the domain model.
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn sample_stdio() -> McpServer {
        McpServer {
            id: "11111111-2222-3333-4444-555555555555".into(),
            name: "filesystem".into(),
            transport: McpTransport::Stdio,
            command: Some("npx".into()),
            args: vec!["-y".into(), "@mcp/filesystem".into()],
            env: HashMap::from([("ROOT".into(), "/tmp".into())]),
            url: None,
            enabled: true,
            created_at: 1_700_000_000,
        }
    }

    fn sample_http() -> McpServer {
        McpServer {
            id: "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee".into(),
            name: "remote-search".into(),
            transport: McpTransport::Http,
            command: None,
            args: vec![],
            env: HashMap::new(),
            url: Some("https://mcp.example.com/sse".into()),
            enabled: false,
            created_at: 1_700_000_001,
        }
    }

    // ----- construction -----

    #[test]
    fn new_populates_uuid_and_created_at_and_enabled_true() {
        let s = McpServer::new("fs", McpTransport::Stdio, Some("npx".into()), None);
        assert!(is_uuid_like(&s.id), "id should look like a UUID: {}", s.id);
        assert_eq!(s.name, "fs");
        assert!(s.enabled);
        assert!(s.created_at > 1_700_000_000);
        assert!(s.args.is_empty());
        assert!(s.env.is_empty());
        assert!(s.command.is_some());
        assert!(s.url.is_none());
    }

    #[test]
    fn new_for_http_sets_url_and_keeps_command_none() {
        let s = McpServer::new(
            "remote",
            McpTransport::Http,
            None,
            Some("https://x.example/sse".into()),
        );
        assert!(s.url.is_some());
        assert!(s.command.is_none());
    }

    // ----- validation -----

    #[test]
    fn validate_rejects_empty_name() {
        let mut s = sample_stdio();
        s.name = "".into();
        let err = s.validate().unwrap_err();
        assert!(matches!(err, McpError::InvalidField(m) if m.contains("name")));
    }

    #[test]
    fn validate_rejects_stdio_with_no_command() {
        let mut s = sample_stdio();
        s.command = None;
        let err = s.validate().unwrap_err();
        assert!(matches!(err, McpError::InvalidField(m) if m.contains("stdio")));
    }

    #[test]
    fn validate_rejects_http_with_no_url() {
        let mut s = sample_http();
        s.url = None;
        let err = s.validate().unwrap_err();
        assert!(matches!(err, McpError::InvalidField(m) if m.contains("http")));
    }

    #[test]
    fn validate_accepts_valid_stdio() {
        sample_stdio().validate().expect("valid stdio");
    }

    #[test]
    fn validate_accepts_valid_http() {
        sample_http().validate().expect("valid http");
    }

    // ----- roundtrip -----

    #[test]
    fn roundtrip_preserves_all_fields() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join("fs.json");
        let original = sample_stdio();
        original.to_json_file(&path).unwrap();
        let restored = McpServer::from_json_file(&path).unwrap();
        assert_eq!(restored, original);
    }

    #[test]
    fn roundtrip_preserves_all_fields_http() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join("http.json");
        let original = sample_http();
        original.to_json_file(&path).unwrap();
        let restored = McpServer::from_json_file(&path).unwrap();
        assert_eq!(restored, original);
    }

    // ----- (de)serialisation edge cases -----

    #[test]
    fn serialise_uses_snake_case_field_names() {
        let s = sample_stdio();
        let json = serde_json::to_string_pretty(&s).unwrap();
        assert!(json.contains("\"created_at\""));
        assert!(json.contains("\"enabled\""));
        // command is skipped when None (Option serde option)
        let http = sample_http();
        let json_http = serde_json::to_string_pretty(&http).unwrap();
        assert!(!json_http.contains("\"command\""));
        assert!(json_http.contains("\"url\""));
    }

    #[test]
    fn serialise_transport_uses_lowercase_tag() {
        let s = sample_stdio();
        let v: serde_json::Value = serde_json::to_value(&s).unwrap();
        assert_eq!(v["transport"]["type"], "stdio");
        let h = sample_http();
        let v: serde_json::Value = serde_json::to_value(&h).unwrap();
        assert_eq!(v["transport"]["type"], "http");
    }

    #[test]
    fn deserialise_transport_from_lowercase_tag() {
        let json = r#"{
            "id": "11111111-2222-3333-4444-555555555555",
            "name": "fs",
            "transport": { "type": "stdio" },
            "command": "npx",
            "args": [],
            "env": {},
            "enabled": true,
            "created_at": 1
        }"#;
        let s: McpServer = serde_json::from_str(json).unwrap();
        assert_eq!(s.transport, McpTransport::Stdio);
        assert_eq!(s.command.as_deref(), Some("npx"));
    }

    #[test]
    fn deserialise_with_missing_enabled_defaults_true() {
        let json = r#"{
            "id": "11111111-2222-3333-4444-555555555555",
            "name": "fs",
            "transport": { "type": "stdio" },
            "command": "npx",
            "args": [],
            "env": {},
            "created_at": 1
        }"#;
        let s: McpServer = serde_json::from_str(json).unwrap();
        assert!(s.enabled, "missing `enabled` should default to true");
    }

    #[test]
    fn deserialise_with_missing_args_and_env_defaults_to_empty() {
        let json = r#"{
            "id": "11111111-2222-3333-4444-555555555555",
            "name": "fs",
            "transport": { "type": "stdio" },
            "command": "npx",
            "enabled": true,
            "created_at": 1
        }"#;
        let s: McpServer = serde_json::from_str(json).unwrap();
        assert!(s.args.is_empty());
        assert!(s.env.is_empty());
    }

    #[test]
    fn deserialise_http_with_missing_url_succeeds_validation_will_fail() {
        // Deserialise alone does NOT enforce validation — only
        // from_json_file does. We keep these separate so a partially-
        // populated entry on disk can still be loaded for the UI to
        // show as "incomplete".
        let json = r#"{
            "id": "11111111-2222-3333-4444-555555555555",
            "name": "remote",
            "transport": { "type": "http" },
            "enabled": true,
            "created_at": 1
        }"#;
        let s: McpServer = serde_json::from_str(json).unwrap();
        assert_eq!(s.transport, McpTransport::Http);
        assert!(s.url.is_none());
        // from_json_file runs validate() and would fail.
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join("incomplete.json");
        std::fs::write(&path, json).unwrap();
        let err = McpServer::from_json_file(&path).unwrap_err();
        assert!(matches!(err, McpError::InvalidField(_)));
    }

    // ----- from_json_file error paths -----

    #[test]
    fn from_json_file_handles_nonexistent_path() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join("does-not-exist.json");
        let err = McpServer::from_json_file(&path).unwrap_err();
        assert!(matches!(err, McpError::Io(_)));
    }

    #[test]
    fn from_json_file_handles_invalid_transport_tag() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join("bad.json");
        std::fs::write(
            &path,
            r#"{
                "id": "11111111-2222-3333-4444-555555555555",
                "name": "x",
                "transport": { "type": "websocket" },
                "created_at": 1
            }"#,
        )
        .unwrap();
        let err = McpServer::from_json_file(&path).unwrap_err();
        assert!(matches!(err, McpError::Json(_)));
    }

    #[test]
    fn to_json_file_uses_2_space_indent() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join("pretty.json");
        sample_stdio().to_json_file(&path).unwrap();
        let raw = std::fs::read_to_string(&path).unwrap();
        assert!(raw.contains("  \"id\""), "expected 2-space indent:\n{raw}");
    }
}
