//! OptimizationFinding — domain model for F18 (M2.9).
//!
//! SPEC §3.5 + §5.11 + §6.7 define the 优化检查 contract; this module
//! owns the Rust representation. The on-disk shape is N/A — findings
//! live in memory only (regenerated on each `scan_optimizations` call)
//! and the UI selects a subset to apply by `id`.
//!
//! ## Conventions
//!
//! - `id` is a fresh uuid v4 each time `scan` runs. Re-running `scan`
//!   yields different ids for the "same" issue — this is intentional:
//!   findings are NOT a stable cross-call identity. The UI passes
//!   ids back to `apply_findings` from the same scan response;
//!   stale ids return `ApplyResult::not_found`.
//! - `severity` matches SPEC §6.7's 三级分类:
//!   - `Info`     ≈ "需确认"(用户偏好)+"已扫描跳过"
//!   - `Warning`  ≈ "安全 / 可一键应用"
//!   - `Error`    = 不修会引发功能损坏(active provider 缺失等)
//! - `auto_apply` matches the "rule's apply 是否真改文件":
//!   true  = `OptimizerRule::apply` 走 fs_atomic 写盘
//!   false = `OptimizerRule::apply` 返回 `ApplyResult { applied: false,
//!           error: Some("需用户介入,跳到 X 页") }`
//!
//! ## Why a fresh struct (not piggy-back on Provider / McpServer)
//!
//! A finding is *cross-cutting* — it can reference a provider file,
//! settings.json, mcp.json, or a backup directory. Embedding it in
//! any one domain entity would tie the optimizer to that entity's
//! lifecycle. Instead the finding carries `affected_path` as a free
//! string the UI displays.

use serde::{Deserialize, Serialize};

/// One issue surfaced by the optimizer scan.
///
/// Generated by `infrastructure::optimizer_rules::OptimizerRule::check`,
/// returned to the frontend by the `scan_optimizations` Tauri command,
/// and passed back (by id) to `apply_optimizations`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct OptimizationFinding {
    /// Fresh uuid v4 — regenerated each scan. The UI uses this as
    /// the React list key and as the selection id passed to
    /// `apply_optimizations`.
    pub id: String,
    /// Stable rule identifier (e.g. `ORPHAN_PROVIDER`). Used by the
    /// service to dispatch to the right `OptimizerRule::apply`.
    pub rule_id: String,
    /// SPEC §6.7 risk level — drives the UI grouping + default
    /// checkbox state.
    pub severity: Severity,
    /// Short, user-facing title (中文 per CLAUDE.md project HTML rule).
    pub title: String,
    /// Longer explanation; the UI may render this in a hover tooltip
    /// or expand panel.
    pub description: String,
    /// File path or JSON pointer-ish string the user can show to
    /// identify which thing is affected (e.g.
    /// `~/.claude/settings.json:env.ANTHROPIC_BASE_URL`).
    pub affected_path: String,
    /// What the user (or the auto-apply) should do — "删除"/"重命名"/etc.
    pub suggested_action: String,
    /// Whether `OptimizerRule::apply` actually modifies a file. UI
    /// uses this to disable the [应用 N 项] button for findings
    /// that need manual intervention.
    pub auto_apply: bool,
}

/// SPEC §6.7 三级分类. Lowercase on the wire to match TS frontend.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Severity {
    /// "需确认" / "已扫描但跳过" — informational, user decides.
    Info,
    /// "安全" — common cleanup, default checked in UI.
    Warning,
    /// Functional break — must fix or Claude Code won't run.
    Error,
}

/// Result of applying one finding. Returned in a `Vec<ApplyResult>`
/// from `apply_optimizations`; the UI shows a green/red row per entry.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct ApplyResult {
    /// Echoes the input id so the UI can match by index.
    pub finding_id: String,
    /// `true` if the rule's `apply` succeeded. `false` for both
    /// "manual fix needed" findings and outright failures — the
    /// `error` field disambiguates.
    pub applied: bool,
    /// Path to the `.bak.<ts>` snapshot if the apply rewrote a file.
    /// `None` for manual / failed / no-write applies.
    pub backup_path: Option<String>,
    /// User-readable error / explanation. `None` only when
    /// `applied == true`.
    pub error: Option<String>,
}

impl ApplyResult {
    /// Helper for "I made the change" outcomes.
    pub fn ok(finding_id: impl Into<String>, backup_path: Option<String>) -> Self {
        Self {
            finding_id: finding_id.into(),
            applied: true,
            backup_path,
            error: None,
        }
    }

    /// Helper for "I refused to change anything" outcomes (manual rules
    /// or hard errors). `applied` is `false`; `error` is mandatory.
    pub fn manual(finding_id: impl Into<String>, reason: impl Into<String>) -> Self {
        Self {
            finding_id: finding_id.into(),
            applied: false,
            backup_path: None,
            error: Some(reason.into()),
        }
    }
}

// ---------------------------------------------------------------------------
// Tests — TDD coverage for the domain model.
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn severity_serializes_lowercase() {
        let v = serde_json::to_value(Severity::Info).unwrap();
        assert_eq!(v, serde_json::Value::String("info".into()));
        let v = serde_json::to_value(Severity::Warning).unwrap();
        assert_eq!(v, serde_json::Value::String("warning".into()));
        let v = serde_json::to_value(Severity::Error).unwrap();
        assert_eq!(v, serde_json::Value::String("error".into()));
    }

    #[test]
    fn severity_deserializes_lowercase() {
        let s: Severity = serde_json::from_str("\"info\"").unwrap();
        assert_eq!(s, Severity::Info);
        let s: Severity = serde_json::from_str("\"warning\"").unwrap();
        assert_eq!(s, Severity::Warning);
        let s: Severity = serde_json::from_str("\"error\"").unwrap();
        assert_eq!(s, Severity::Error);
    }

    #[test]
    fn finding_roundtrips() {
        let f = OptimizationFinding {
            id: "00000000-0000-0000-0000-000000000001".into(),
            rule_id: "ORPHAN_PROVIDER".into(),
            severity: Severity::Warning,
            title: "孤儿 provider".into(),
            description: "settings.json 引用了一个不存在的 provider".into(),
            affected_path: "~/.claude/settings.json".into(),
            suggested_action: "删除引用或重建 provider".into(),
            auto_apply: false,
        };
        let json = serde_json::to_string(&f).unwrap();
        // snake_case on the wire
        assert!(json.contains("\"rule_id\""));
        assert!(json.contains("\"affected_path\""));
        assert!(json.contains("\"suggested_action\""));
        assert!(json.contains("\"auto_apply\""));
        // severity is lowercase
        assert!(json.contains("\"severity\":\"warning\""));
        let restored: OptimizationFinding = serde_json::from_str(&json).unwrap();
        assert_eq!(restored, f);
    }

    #[test]
    fn apply_result_ok_helper_marks_applied() {
        let r = ApplyResult::ok("fid-1", Some("/tmp/x.bak.20260619-100000".into()));
        assert!(r.applied);
        assert_eq!(r.finding_id, "fid-1");
        assert!(r.error.is_none());
        assert!(r.backup_path.is_some());
    }

    #[test]
    fn apply_result_manual_helper_marks_not_applied() {
        let r = ApplyResult::manual("fid-2", "需用户去切换页解决");
        assert!(!r.applied);
        assert_eq!(r.finding_id, "fid-2");
        assert!(r.backup_path.is_none());
        assert_eq!(r.error.as_deref(), Some("需用户去切换页解决"));
    }

    #[test]
    fn apply_result_serializes_snake_case_with_lowercase_severity_unaffected() {
        // ApplyResult itself doesn't carry severity; verify its
        // own field shape.
        let r = ApplyResult::ok("fid-3", None);
        let json = serde_json::to_string(&r).unwrap();
        assert!(json.contains("\"finding_id\":\"fid-3\""));
        assert!(json.contains("\"applied\":true"));
        assert!(json.contains("\"backup_path\":null"));
        assert!(json.contains("\"error\":null"));
    }

    #[test]
    fn finding_with_empty_optional_fields_still_serializes() {
        let f = OptimizationFinding {
            id: "id".into(),
            rule_id: "X".into(),
            severity: Severity::Info,
            title: "".into(),
            description: "".into(),
            affected_path: "".into(),
            suggested_action: "".into(),
            auto_apply: true,
        };
        let _ = serde_json::to_string(&f).unwrap();
    }
}
