/**
 * F6 — MCP 管理 (M2.5).
 *
 * TypeScript mirror of the Rust `McpServer` struct
 * (`src-tauri/src/domain/mcp_server.rs`). Field names use
 * snake_case to match the Rust `#[serde(rename_all = "snake_case")]`
 * on the Rust side; this keeps the IPC contract obvious in both
 * files.
 *
 * The on-disk format (`~/.claude/mcp.json`) is *not* this shape:
 * it's a map of name → entry. The McpService handles the disk ↔
 * struct translation; the frontend always works with `McpServer[]`.
 */

export type McpTransport = 'stdio' | 'http';

export interface McpServer {
  /** UUID — stable list/toggle key, generated by `McpServer::new`. */
  id: string;
  /** Display name; ALSO the on-disk mcpServers map key. */
  name: string;
  /** Transport discriminant. Stdio uses command/args/env; Http uses url. */
  transport: McpTransport;
  /** Stdio transport only — the executable to run. */
  command?: string;
  /** Stdio transport only — CLI args. */
  args: string[];
  /** Stdio transport only — env vars. */
  env: Record<string, string>;
  /** Http transport only — SSE/streamable-http endpoint. */
  url?: string;
  /** Whether the server is enabled. */
  enabled: boolean;
  /** Unix seconds (matches `Provider.created_at`). */
  created_at: number;
}

/**
 * Result of `listMcpServersWithWarnings` — includes a parse warning
 * for the UI to surface as a non-fatal InfoBar.
 */
export interface ListMcpServersResult {
  servers: McpServer[];
  warning: string | null;
}
